version: '3'
services:
  appweb:
    build: ./appweb
    ports:
      - 80:80
    env_file: .env
    environment:
      DATABASE_HOST: db
    depends_on:
      - db
    volumes:
      - ./data/html:/var/www/html
  db:
    build: ./db
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/
      - ./db/initial.sql:/docker-entrypoint-initdb.d/initial.sql
volumes:
    db-data:
